In [40]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

# Creating tensors

`torch.tensor` creates the tensor    
`TENSOR.item` returns the python type data from the`torch.tensor`


In [41]:
scalar = torch.tensor(7)

vector = torch.tensor([89,69])

MATRIX = torch.tensor(
    [[12, 21, 12],
    [12, 12, 12]]
)

TENSOR = torch.tensor(
    [[[12, 21, 12],
    [12, 12, 12],
    [23, 4, 334]]]
)

In [42]:
scalar.ndim, vector.ndim, MATRIX.ndim, TENSOR.ndim

(0, 1, 2, 3)

SIZE of a tensor - the size of a tensor is such that first number will give us the number of blocks, and following numbers will give us number of sub-blocks and so on, last two numbers will give us the dimension of matrices and 3rd last number will give us the number of matrices in the last sub-block.

In [43]:
scalar.shape, vector.shape, MATRIX.shape, TENSOR.shape

(torch.Size([]), torch.Size([2]), torch.Size([2, 3]), torch.Size([1, 3, 3]))

Also interestingly there are two functions,   
`torch.tensor` which will infer the dtype as is    
`torch.Tensor` which is basically `torch.FloatTensor` 

this is a rabbit of some sort, Tensor is faster then tensor, also I have found out that `torch.Tensor` generates a tensor with that number of random elements.
so, `torch.Tensor(7)` will generate a vector with 7 random numbers.

In [44]:
torch.tensor(7), torch.Tensor(7)

(tensor(7),
 tensor([-4.4826e+05,  3.1273e-41,  0.0000e+00,  0.0000e+00, -7.1458e-04,
          3.1266e-41, -7.5295e-04]))

## Random tensors
Creating random tensors is useful in NNets because we can generate a initial weights and biases randomly. and start from there.

In [45]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.1361, 0.6457, 0.5182],
        [0.5545, 0.2711, 0.8037],
        [0.1177, 0.9990, 0.0287]])

Color image tensors are generally of tensor dim = 3, 3 dimensional tensors, each dimensions representing the activation of different color channels.

In [46]:
random_image_tensor = torch.rand( size = (224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones
zeros and ones tensors for masking and manipulating the tensor via multiplication of summation.

In [47]:
zeros = torch.zeros(3, 3) #? 3x3 matrix of zeros
ones = torch.ones(3, 3) #? 3x3 matrix of ones

## Range Tensors and Tansor-like

In [48]:
step_tensor = torch.arange(start = 0, end = 10, step = 2) #? 0 to 10 with step 2
step_tensor

tensor([0, 2, 4, 6, 8])

create a zeros tensor but with the shape of a input tensor

In [49]:
step_tensor_like = torch.zeros_like(input=step_tensor) 
step_tensor_like

tensor([0, 0, 0, 0, 0])

# Tensor Data Types
https://pytorch.org/docs/stable/tensors.html


In [50]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #* defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, #* defaults to None, which uses the default tensor type
                               requires_grad=False) #* if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

You can get the information about the tensor by `TENSOR.shpae, TENSOR.dtype, TENSOR.device`

Converting the dtype of the tensor

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half would also work
float_16_tensor.dtype

torch.float16

# Tensor operations
All the basic operations works as you expect the only thing you need to be careful is with some linear algebra operations like dot product, hadamard product and so on

## Matrix Multiplication

Dot product in linear algebra, no. of rows of the first tensor should match no. column of second tensor.

In [55]:
tensor = torch.tensor([1, 2, 3])

In [56]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.21 ms, sys: 162 µs, total: 1.38 ms
Wall time: 3.2 ms


tensor(14)

In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 809 µs, sys: 108 µs, total: 917 µs
Wall time: 925 µs


tensor(14)

`torch.matmul` is faster than the for-loop. this is a general guidline in all the library function everywhere. **-DO NOT USE RAW LOOPS-**

### Transpose function

Can be useful when multiplying the same rectangular tensor.    
- `torch.transpose (TENSOR, dim0, dim1)` is a way to transpose in a dimension for 2d the obvious transpose is between 0th dim and 1st dim. In 3d or 4d tensor it will transpose the appropriate dims, for example change 3rd with 4th in 5dim tensor.    
- `Tensor.T` is a simplified transpose. always transpose last two dimensions

In [120]:
tensor = torch.rand(3, 1, 2)
tensor1 = torch.transpose(tensor, 1, 2)
tensor, tensor1, tensor.mT

(tensor([[[0.6094, 0.9322]],
 
         [[0.7446, 0.1235]],
 
         [[0.2225, 0.7060]]]),
 tensor([[[0.6094],
          [0.9322]],
 
         [[0.7446],
          [0.1235]],
 
         [[0.2225],
          [0.7060]]]),
 tensor([[[0.6094],
          [0.9322]],
 
         [[0.7446],
          [0.1235]],
 
         [[0.2225],
          [0.7060]]]))