In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

# Creating tensors

`torch.tensor` creates the tensor    
`TENSOR.item` returns the python type data from the`torch.tensor`


In [3]:
scalar = torch.tensor(7)

vector = torch.tensor([89,69])

MATRIX = torch.tensor(
    [[12, 21, 12],
    [12, 12, 12]]
)

TENSOR = torch.tensor(
    [[[12, 21, 12],
    [12, 12, 12],
    [23, 4, 334]]]
)

In [4]:
scalar.ndim, vector.ndim, MATRIX.ndim, TENSOR.ndim

(0, 1, 2, 3)

SIZE of a tensor - the size of a tensor is such that first number will give us the number of blocks, and following numbers will give us number of sub-blocks and so on, last two numbers will give us the dimension of matrices and 3rd last number will give us the number of matrices in the last sub-block.

In [5]:
scalar.shape, vector.shape, MATRIX.shape, TENSOR.shape

(torch.Size([]), torch.Size([2]), torch.Size([2, 3]), torch.Size([1, 3, 3]))

Also interestingly there are two functions,   
`torch.tensor` which will infer the dtype as is    
`torch.Tensor` which is basically `torch.FloatTensor` 

this is a rabbit of some sort, Tensor is faster then tensor, also I have found out that `torch.Tensor` generates a tensor with that number of random elements.
so, `torch.Tensor(7)` will generate a vector with 7 random numbers.

In [6]:
torch.tensor(7), torch.Tensor(7)

(tensor(7),
 tensor([-1.1636e-21,  3.1262e-41,  0.0000e+00,  0.0000e+00,         nan,
          0.0000e+00,  1.8617e+25]))

## Random tensors
Creating random tensors is useful in NNets because we can generate a initial weights and biases randomly. and start from there.

In [7]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.1034, 0.3459, 0.2091],
        [0.9538, 0.1410, 0.3237],
        [0.6385, 0.6156, 0.1496]])

Color image tensors are generally of tensor dim = 3, 3 dimensional tensors, each dimensions representing the activation of different color channels.

In [8]:
random_image_tensor = torch.rand( size = (224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones
zeros and ones tensors for masking and manipulating the tensor via multiplication of summation.

In [9]:
zeros = torch.zeros(3, 3) #? 3x3 matrix of zeros
ones = torch.ones(3, 3) #? 3x3 matrix of ones

## Range Tensors and Tansor-like

In [10]:
step_tensor = torch.arange(start = 0, end = 10, step = 2) #? 0 to 10 with step 2
step_tensor

tensor([0, 2, 4, 6, 8])

create a zeros tensor but with the shape of a input tensor

In [11]:
step_tensor_like = torch.zeros_like(input=step_tensor) 
step_tensor_like

tensor([0, 0, 0, 0, 0])

# Tensor Data Types
https://pytorch.org/docs/stable/tensors.html


In [12]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #* defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, #* defaults to None, which uses the default tensor type
                               requires_grad=False) #* if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

You can get the information about the tensor by `TENSOR.shpae, TENSOR.dtype, TENSOR.device`

Converting the dtype of the tensor

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half would also work
float_16_tensor.dtype

torch.float16

# Tensor operations
All the basic operations works as you expect the only thing you need to be careful is with some linear algebra operations like dot product, hadamard product and so on

## Matrix Multiplication

Dot product in linear algebra, no. of rows of the first tensor should match no. column of second tensor.

In [14]:
tensor = torch.tensor([1, 2, 3])

In [15]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 913 µs, sys: 447 µs, total: 1.36 ms
Wall time: 5.62 ms


tensor(14)

In [16]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 537 µs, sys: 262 µs, total: 799 µs
Wall time: 4.96 ms


tensor(14)

`torch.matmul` is faster than the for-loop. this is a general guidline in all the library function everywhere. **-DO NOT USE RAW LOOPS-**

### Transpose function

Can be useful when multiplying the same rectangular tensor.    
- `torch.transpose (TENSOR, dim0, dim1)` is a way to transpose in a dimension for 2d the obvious transpose is between 0th dim and 1st dim. In 3d or 4d tensor it will transpose the appropriate dims, for example change 3rd with 4th in 5dim tensor.    
- `Tensor.T` is a simplified transpose. always transpose last two dimensions

In [17]:
tensor = torch.rand(3, 1, 2)
tensor1 = torch.transpose(tensor, 1, 2)
tensor, tensor1, tensor.mT

(tensor([[[0.4899, 0.0637]],
 
         [[0.3548, 0.9611]],
 
         [[0.3163, 0.4651]]]),
 tensor([[[0.4899],
          [0.0637]],
 
         [[0.3548],
          [0.9611]],
 
         [[0.3163],
          [0.4651]]]),
 tensor([[[0.4899],
          [0.0637]],
 
         [[0.3548],
          [0.9611]],
 
         [[0.3163],
          [0.4651]]]))

### min, max, mean, sum

mean function only work on float type objects

In [32]:
x = torch.arange(start = 0, end = 11, step = 2).type(torch.float32)
x , x.dtype

(tensor([ 0.,  2.,  4.,  6.,  8., 10.]), torch.float32)

In [33]:
torch.min(x), torch.max(x), torch.mean(x), torch.sum(x)

(tensor(0.), tensor(10.), tensor(5.), tensor(30.))

In [34]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

### Reshaping, stacking, squeezing, unsqueezing tensors

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 


In [46]:
x = torch.arange(start = 0, end = 11, step = 2).type(torch.float32)
x, x.shape

(tensor([ 0.,  2.,  4.,  6.,  8., 10.]), torch.Size([6]))

reshape will add or remove the dimensions if compatible, that is total number of the elements must match

In [45]:
x_reshape = x.reshape (2, 3)
x_reshape

tensor([[ 5.,  2.,  4.],
        [ 5.,  8., 10.]])

view will have the same memory address. so changing the view will change the original tensor, but they are not the same tensors. The dimension of the tensors can be different.

In [47]:
z = x.view(2, 3)
z[:, 0] = 5
z , x

(tensor([[ 5.,  2.,  4.],
         [ 5.,  8., 10.]]),
 tensor([ 5.,  2.,  4.,  5.,  8., 10.]))