# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor

# Perform matrix multiplication 
y = torch.rand(1, 7)
torch.matmul(x, y.mT)

tensor([[1.1341],
        [1.8480],
        [1.3624],
        [1.7587],
        [1.5549],
        [1.8863],
        [1.3524]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [23]:
# Set manual seed
RANDOM_SEED = 43

# Create two random tensors

torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(5, 3)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(5, 3)

# Matrix multiply tensors

tensor_C = torch.matmul(tensor_A, tensor_B.mT)
tensor_C

tensor([[1.0930, 0.2653, 0.9698, 0.5916, 0.8356],
        [0.2653, 0.1491, 0.2785, 0.3670, 0.3048],
        [0.9698, 0.2785, 0.9125, 0.5315, 0.7438],
        [0.5916, 0.3670, 0.5315, 1.2910, 0.8976],
        [0.8356, 0.3048, 0.7438, 0.8976, 0.8431]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(RANDOM_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
RANDOM_SEED = 43

# Check for access to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [29]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.mT)

### 8. Find the maximum and minimum values of the output of 7.

In [31]:
# Find max
print(torch.max(tensor_C))

# Find min
torch.min(tensor_C)

tensor(0.6535)


tensor(0.5814)

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max
print (torch.argmax(tensor_C))

# Find arg min
torch.argmin(tensor_C)

tensor(0)


tensor(3)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
RANDOM_SEED = 42

# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_B = torch.squeeze(tensor_A)


# Print out tensors and their shapes
tensor_A, tensor_B, tensor_A.shape, tensor_B.shape

(tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
            0.9408, 0.1332]]]]),
 tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))